name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests-ios:
    name: Build and Test on iOS
    runs-on: macos-latest
    strategy:
      matrix:
        target: ['Example', 'Example-Hermes']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - name: Build
        env:
          TEST_SCHEME: ${{ matrix.target }}
          TEST_PLATFORM: ${{ 'iOS Simulator' }}
        run: |
          set -eo pipefail
          yarn bootstrap
          TEST_DEVICE=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
          cd example/ios && xcodebuild test -scheme "$TEST_SCHEME" -destination "platform=$TEST_PLATFORM,name=$TEST_DEVICE" -workspace Example.xcworkspace
