name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests-ios:
    name: Build and Test on iOS
    runs-on: macos-latest
    strategy:
      matrix:
        target: ['Example', 'Example-Hermes']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Build
        env:
          scheme: ${{ matrix.target }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          set -eo pipefail
          set -x
          yarn install
          cd example/ios && xcodebuild test -scheme "$scheme"
